//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.NonBusinessModel.Model.Icom.ItinsyncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int auditID { get; set; }
        public Nullable<int> eventCode { get; set; }
        public string description { get; set; }
        public string additionalDetails { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> transDateTime { get; set; }
        public string parentRef { get; set; }
        public string userName { get; set; }
        public Nullable<int> vendorID { get; set; }
        public Nullable<long> transID { get; set; }
    
        public virtual BusinessTransaction BusinessTransaction { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
