//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.NonBusinessModel.Model.Icom.ItinsyncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchManagement
    {
        public long ID { get; set; }
        public string JobName { get; set; }
        public Nullable<System.TimeSpan> IntervalTime { get; set; }
        public Nullable<bool> Repeatable { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
