//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.NonBusinessModel.Model.Icom.ItinsyncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailConfig
    {
        public int emailConfigID { get; set; }
        public string hostName { get; set; }
        public Nullable<int> portNo { get; set; }
        public string userEmail { get; set; }
        public string password { get; set; }
        public string fromAddress { get; set; }
        public Nullable<byte> enableSSL { get; set; }
        public Nullable<long> transID { get; set; }
    
        public virtual BusinessTransaction BusinessTransaction { get; set; }
    }
}
