//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.NonBusinessModel.Model.Icom.ItinsyncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup
    {
        public long lookUpID { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string text { get; set; }
        public string fr { get; set; }
        public string sp { get; set; }
        public string ud { get; set; }
        public Nullable<long> transID { get; set; }
    }
}
