//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.NonBusinessModel.Model.Icom.ItinsyncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupTran
    {
        public long lookupTransID { get; set; }
        public string code { get; set; }
        public string value { get; set; }
        public string lang { get; set; }
        public Nullable<long> transID { get; set; }
    }
}
