//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.NonBusinessModel.Model.Icom.ItinsyncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.UserTeams = new HashSet<UserTeam>();
        }
    
        public int teamID { get; set; }
        public string teamName { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> vendorID { get; set; }
        public Nullable<long> transID { get; set; }
    
        public virtual BusinessTransaction BusinessTransaction { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTeam> UserTeams { get; set; }
    }
}
