//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.NonBusinessModel.Model.Icom.ItinsyncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public long userRoleID { get; set; }
        public Nullable<long> userID { get; set; }
        public Nullable<long> role { get; set; }
        public Nullable<long> transID { get; set; }
    }
}
