//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.NonBusinessModel.Model.Icom.ItinsyncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTeam
    {
        public int userTeamID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> teamID { get; set; }
        public Nullable<long> transID { get; set; }
    
        public virtual BusinessTransaction BusinessTransaction { get; set; }
        public virtual Team Team { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
