//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.NonBusinessModel.Model.Icom.ItinsyncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAccount()
        {
            this.Audits = new HashSet<Audit>();
            this.UserPermissions = new HashSet<UserPermission>();
            this.UserPermissionProfiles = new HashSet<UserPermissionProfile>();
            this.UserStores = new HashSet<UserStore>();
            this.UserTeams = new HashSet<UserTeam>();
            this.vendordevices = new HashSet<vendordevice>();
        }
    
        public int userID { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public Nullable<int> role { get; set; }
        public Nullable<int> loginCount { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> lastLogin { get; set; }
        public Nullable<bool> isLock { get; set; }
        public string userPhone { get; set; }
        public string userEmail { get; set; }
        public long transID { get; set; }
        public string lang { get; set; }
        public string timeZone { get; set; }
        public string countryCode { get; set; }
        public Nullable<int> vendorID { get; set; }
        public Nullable<int> mobileProvider { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> roleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audit> Audits { get; set; }
        public virtual BusinessTransaction BusinessTransaction { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPermissionProfile> UserPermissionProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserStore> UserStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTeam> UserTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vendordevice> vendordevices { get; set; }
    }
}
