//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.NonBusinessModel.Model.Icom.ItinsyncModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.Audits = new HashSet<Audit>();
            this.Teams = new HashSet<Team>();
            this.UserAccounts = new HashSet<UserAccount>();
            this.vendordevices = new HashSet<vendordevice>();
        }
    
        public int vendorID { get; set; }
        public string name { get; set; }
        public Nullable<int> primaryRole { get; set; }
        public string contactPerson { get; set; }
        public string additionalService { get; set; }
        public Nullable<int> activeFrom { get; set; }
        public Nullable<int> activeTo { get; set; }
        public Nullable<System.DateTime> transDateTime { get; set; }
        public Nullable<long> transID { get; set; }
        public string pFix { get; set; }
        public string ranking { get; set; }
        public string refNo { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<byte> contactMethod { get; set; }
        public Nullable<int> vat { get; set; }
        public Nullable<int> tax { get; set; }
        public string preferredLanguage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audit> Audits { get; set; }
        public virtual BusinessTransaction BusinessTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vendordevice> vendordevices { get; set; }
    }
}
