// <auto-generated />
namespace Intinsync.MvcForms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_commits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_commits));
        
        string IMigrationMetadata.Id
        {
            get { return "201803021314102_initial_commits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
