//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.BusinessModel.Model.Icom.CustomerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationCode
    {
        public int id { get; set; }
        public string DOMAINHOST { get; set; }
        public string BASE_LOCATION { get; set; }
        public string PRODUCTION_MODE { get; set; }
        public Nullable<long> CACHECOUNT { get; set; }
        public Nullable<long> transID { get; set; }
        public string companyName { get; set; }
    }
}
