//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.BusinessModel.Model.Icom.CustomerModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kvcContext : DbContext
    {
        public kvcContext()
            : base("name=kvcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationCode> ApplicationCodes { get; set; }
        public virtual DbSet<CrossTable_businesstransaction> CrossTable_businesstransaction { get; set; }
        public virtual DbSet<CrossTable_pagename> CrossTable_pagename { get; set; }
        public virtual DbSet<CrossTable_vendor> CrossTable_vendor { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentAlert> DocumentAlerts { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<XDocumentDefinition> XDocumentDefinitions { get; set; }
        public virtual DbSet<XDocumentFrequency> XDocumentFrequencies { get; set; }
        public virtual DbSet<XDocumentReferedContent> XDocumentReferedContents { get; set; }
        public virtual DbSet<XDocumentRole> XDocumentRoles { get; set; }
        public virtual DbSet<XDocumentRoleAlert> XDocumentRoleAlerts { get; set; }
        public virtual DbSet<XDocumentRoleRoute> XDocumentRoleRoutes { get; set; }
        public virtual DbSet<XDocumentRoute> XDocumentRoutes { get; set; }
        public virtual DbSet<XDocumentRouteUser> XDocumentRouteUsers { get; set; }
        public virtual DbSet<XDocumentSection> XDocumentSections { get; set; }
        public virtual DbSet<XDocumentStore> XDocumentStores { get; set; }
        public virtual DbSet<XDocumentTable> XDocumentTables { get; set; }
        public virtual DbSet<XDocumentTableContent> XDocumentTableContents { get; set; }
        public virtual DbSet<XDocumentTableTD> XDocumentTableTDs { get; set; }
        public virtual DbSet<XDocumentTableTR> XDocumentTableTRs { get; set; }
        public virtual DbSet<XDocumentUserAlert> XDocumentUserAlerts { get; set; }
        public virtual DbSet<XReportDefinition> XReportDefinitions { get; set; }
        public virtual DbSet<XReportSection> XReportSections { get; set; }
        public virtual DbSet<XReportTable> XReportTables { get; set; }
        public virtual DbSet<XReportTableContent> XReportTableContents { get; set; }
        public virtual DbSet<XReportTableTD> XReportTableTDs { get; set; }
        public virtual DbSet<XReportTableTR> XReportTableTRs { get; set; }
        public virtual DbSet<XTaskDefinition> XTaskDefinitions { get; set; }
    }
}
