//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.BusinessModel.Model.Icom.CustomerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.Documents = new HashSet<Document>();
            this.XDocumentFrequencies = new HashSet<XDocumentFrequency>();
            this.XDocumentRouteUsers = new HashSet<XDocumentRouteUser>();
            this.XDocumentStores = new HashSet<XDocumentStore>();
            this.XDocumentUserAlerts = new HashSet<XDocumentUserAlert>();
        }
    
        public int storeID { get; set; }
        public string name { get; set; }
        public Nullable<int> zipCode { get; set; }
        public string website { get; set; }
        public string storeLink { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Walmart { get; set; }
        public string Fax { get; set; }
        public string storeNo { get; set; }
        public Nullable<int> vendorID { get; set; }
        public Nullable<long> transID { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string storeEmail { get; set; }
    
        public virtual CrossTable_businesstransaction CrossTable_businesstransaction { get; set; }
        public virtual CrossTable_vendor CrossTable_vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XDocumentFrequency> XDocumentFrequencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XDocumentRouteUser> XDocumentRouteUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XDocumentStore> XDocumentStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XDocumentUserAlert> XDocumentUserAlerts { get; set; }
    }
}
