//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.BusinessModel.Model.Icom.CustomerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int taskID { get; set; }
        public string body { get; set; }
        public Nullable<long> transID { get; set; }
        public Nullable<System.DateTime> transDateTime { get; set; }
        public Nullable<int> dueDate { get; set; }
        public Nullable<System.DateTime> deadLineDate { get; set; }
        public Nullable<int> taskDefinitionID { get; set; }
        public Nullable<int> subjectID { get; set; }
        public Nullable<int> teamID { get; set; }
        public Nullable<byte> status { get; set; }
        public string name { get; set; }
        public string parentRef { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> vendorID { get; set; }
        public Nullable<int> dueTime { get; set; }
        public Nullable<int> deadLineTime { get; set; }
        public Nullable<byte> priority { get; set; }
    
        public virtual CrossTable_businesstransaction CrossTable_businesstransaction { get; set; }
        public virtual CrossTable_vendor CrossTable_vendor { get; set; }
        public virtual XTaskDefinition XTaskDefinition { get; set; }
    }
}
