//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.BusinessModel.Model.Icom.CustomerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class XDocumentDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XDocumentDefinition()
        {
            this.Documents = new HashSet<Document>();
            this.XDocumentFrequencies = new HashSet<XDocumentFrequency>();
            this.XDocumentReferedContents = new HashSet<XDocumentReferedContent>();
            this.XDocumentRoles = new HashSet<XDocumentRole>();
            this.XDocumentRoleAlerts = new HashSet<XDocumentRoleAlert>();
            this.XDocumentRoleRoutes = new HashSet<XDocumentRoleRoute>();
            this.XDocumentRoutes = new HashSet<XDocumentRoute>();
            this.XDocumentRouteUsers = new HashSet<XDocumentRouteUser>();
            this.XDocumentSections = new HashSet<XDocumentSection>();
            this.XDocumentStores = new HashSet<XDocumentStore>();
            this.XDocumentUserAlerts = new HashSet<XDocumentUserAlert>();
            this.XReportDefinitions = new HashSet<XReportDefinition>();
        }
    
        public int xDocumentDefinationID { get; set; }
        public string name { get; set; }
        public string rdlcPath { get; set; }
        public string dataTable { get; set; }
        public string parameters { get; set; }
        public Nullable<int> vendorID { get; set; }
        public string storage { get; set; }
        public string email { get; set; }
        public Nullable<long> transID { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> sequential { get; set; }
    
        public virtual CrossTable_businesstransaction CrossTable_businesstransaction { get; set; }
        public virtual CrossTable_vendor CrossTable_vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XDocumentFrequency> XDocumentFrequencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XDocumentReferedContent> XDocumentReferedContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XDocumentRole> XDocumentRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XDocumentRoleAlert> XDocumentRoleAlerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XDocumentRoleRoute> XDocumentRoleRoutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XDocumentRoute> XDocumentRoutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XDocumentRouteUser> XDocumentRouteUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XDocumentSection> XDocumentSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XDocumentStore> XDocumentStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XDocumentUserAlert> XDocumentUserAlerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XReportDefinition> XReportDefinitions { get; set; }
    }
}
