//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.BusinessModel.Model.Icom.CustomerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class XDocumentTableContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XDocumentTableContent()
        {
            this.XDocumentReferedContents = new HashSet<XDocumentReferedContent>();
        }
    
        public int documentTableContentID { get; set; }
        public Nullable<int> tdID { get; set; }
        public Nullable<byte> controlType { get; set; }
        public string controlName { get; set; }
        public string controlID { get; set; }
        public string mask { get; set; }
        public Nullable<bool> isRequired { get; set; }
        public string translation { get; set; }
        public string cssClass { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<long> sequence { get; set; }
        public string lookupName { get; set; }
        public Nullable<byte> colspan { get; set; }
        public string defaultValue { get; set; }
        public string points { get; set; }
        public Nullable<bool> isReadonly { get; set; }
        public string formula { get; set; }
        public string conditions { get; set; }
        public Nullable<int> rows { get; set; }
        public Nullable<int> cells { get; set; }
        public string refControlID { get; set; }
        public Nullable<int> rowspan { get; set; }
        public string src { get; set; }
        public string labelAssociate { get; set; }
        public Nullable<int> documentSectionID { get; set; }
        public Nullable<bool> labelSkip { get; set; }
        public string isReceivedFromLastSubmittedForm { get; set; }
        public Nullable<int> reportFieldColspan { get; set; }
        public Nullable<long> transID { get; set; }
        public string reportHeadingTitle { get; set; }
        public string isNotes { get; set; }
    
        public virtual CrossTable_businesstransaction CrossTable_businesstransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XDocumentReferedContent> XDocumentReferedContents { get; set; }
        public virtual XDocumentTableTD XDocumentTableTD { get; set; }
    }
}
