//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.BusinessModel.Model.Icom.CustomerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class XDocumentTableTD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XDocumentTableTD()
        {
            this.XDocumentTableContents = new HashSet<XDocumentTableContent>();
        }
    
        public int tdID { get; set; }
        public string tdControlID { get; set; }
        public Nullable<int> trID { get; set; }
        public string cssClass { get; set; }
        public Nullable<byte> colspan { get; set; }
        public Nullable<int> tdType { get; set; }
        public Nullable<int> pts { get; set; }
        public Nullable<byte> rowspan { get; set; }
        public Nullable<int> col { get; set; }
        public Nullable<long> transID { get; set; }
    
        public virtual CrossTable_businesstransaction CrossTable_businesstransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XDocumentTableContent> XDocumentTableContents { get; set; }
        public virtual XDocumentTableTR XDocumentTableTR { get; set; }
    }
}
