//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.BusinessModel.Model.Icom.CustomerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class XReportTableContent
    {
        public int reportTableContentID { get; set; }
        public Nullable<int> tdID { get; set; }
        public Nullable<byte> controlType { get; set; }
        public string controlName { get; set; }
        public string controlID { get; set; }
        public string mask { get; set; }
        public Nullable<bool> isRequired { get; set; }
        public string translation { get; set; }
        public string cssClass { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> sequence { get; set; }
        public string lookupName { get; set; }
        public Nullable<byte> colspan { get; set; }
        public string defaultValue { get; set; }
        public string points { get; set; }
        public Nullable<bool> isReadonly { get; set; }
        public string formula { get; set; }
        public string conditions { get; set; }
        public Nullable<byte> rows { get; set; }
        public Nullable<byte> cells { get; set; }
        public string refControlID { get; set; }
        public Nullable<byte> rowspan { get; set; }
        public string src { get; set; }
        public string labelAssociate { get; set; }
        public Nullable<int> documentControlID { get; set; }
        public Nullable<int> documentSectionID { get; set; }
        public string labelSkip { get; set; }
        public string isReceivedFromLastSubmittedForm { get; set; }
        public Nullable<int> reportFieldColspan { get; set; }
        public Nullable<long> transID { get; set; }
        public string reportHeadingTitle { get; set; }
        public string isNotes { get; set; }
    
        public virtual CrossTable_businesstransaction CrossTable_businesstransaction { get; set; }
        public virtual XDocumentSection XDocumentSection { get; set; }
        public virtual XReportTableTD XReportTableTD { get; set; }
    }
}
