//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.BusinessModel.Model.Icom.CustomerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class XReportTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XReportTable()
        {
            this.XReportTableTRs = new HashSet<XReportTableTR>();
        }
    
        public int reportTableID { get; set; }
        public Nullable<int> xReportDefinitionID { get; set; }
        public string cssClass { get; set; }
        public string reportTableHtml { get; set; }
        public Nullable<int> documentSectionID { get; set; }
        public Nullable<byte> parentTableID { get; set; }
        public Nullable<bool> isDifferentReport { get; set; }
        public Nullable<long> transID { get; set; }
    
        public virtual CrossTable_businesstransaction CrossTable_businesstransaction { get; set; }
        public virtual XReportDefinition XReportDefinition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XReportTableTR> XReportTableTRs { get; set; }
    }
}
