//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.BusinessModel.Model.Icom.CustomerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class XReportTableTD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XReportTableTD()
        {
            this.XReportTableContents = new HashSet<XReportTableContent>();
        }
    
        public int reportTdID { get; set; }
        public Nullable<int> reportTrID { get; set; }
        public string tdControlID { get; set; }
        public string cssClass { get; set; }
        public Nullable<int> tdType { get; set; }
        public Nullable<byte> colspan { get; set; }
        public Nullable<byte> rowspan { get; set; }
        public Nullable<byte> col { get; set; }
        public Nullable<long> transID { get; set; }
    
        public virtual CrossTable_businesstransaction CrossTable_businesstransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XReportTableContent> XReportTableContents { get; set; }
        public virtual XReportTableTR XReportTableTR { get; set; }
    }
}
