//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itinsync.BusinessModel.Model.Icom.CustomerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class XTaskDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XTaskDefinition()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int xTaskDefinitionID { get; set; }
        public string name { get; set; }
        public string openService { get; set; }
        public string completeService { get; set; }
        public string parameters { get; set; }
        public Nullable<int> dueDays { get; set; }
        public Nullable<int> deadLineDays { get; set; }
        public string body { get; set; }
        public string route { get; set; }
        public Nullable<int> initiateAuditEvent { get; set; }
        public Nullable<int> inprogressAuditEvent { get; set; }
        public Nullable<int> completeAuditEvent { get; set; }
        public Nullable<long> transID { get; set; }
    
        public virtual CrossTable_businesstransaction CrossTable_businesstransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual XTaskDefinition XTaskDefinition1 { get; set; }
        public virtual XTaskDefinition XTaskDefinition2 { get; set; }
    }
}
